### ISSUE TITLE
Code inside script and style tag should not be considered as content

### ISSUE THREAD

**Issue by FabioRomeiro** [FabioRomeiro/Code_x_Content_Proportionality#1]
Today the calculation considers code inside tags, like `script` and `style`, as being content, when those should be disconsidered.

## Example

Given the code:

```html
<html>
    <h1>An awesome page with lots of javascript</h1>
    <script>
        console.log('hello world')
        
        const code = 'wow'
        if (window) {
            console.log('stuff')
        }
    </script>
</html>
```
## Expected
Code: **75.31%**

Content: **24.68%**

## Today
Code: **18.18%**

Content: **81.82%**

**Comment by Adelabuadeleke** [comment]
hello can you assign this to me to work on it?

**Comment by FabioRomeiro** [comment]
Sure @Adelabuadeleke :smile:

**Comment by Adelabuadeleke** [comment]
Hello Fabio, I reworked the code, however the proportionality I got is:

Code: 82.51%
Content: 17.49%

While able to exclude the style tag and script tag from content.

Would you like me  send a pull request?

**Comment by FabioRomeiro** [comment]
Great! I saw you created the PR, I'll look into it
